// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7r4cH_PVCVBcUomA0CjWDR1m58CjOWjs',
    appId: '1:80954504329:android:f8a7f5b0e65c2d59c8c258',
    messagingSenderId: '80954504329',
    projectId: 'samyeonchoga',
    storageBucket: 'samyeonchoga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNcd5X-NFhoyev-d91CNBte6ReiJ6QOOY',
    appId: '1:80954504329:ios:db6a2ed17b1e9fd2c8c258',
    messagingSenderId: '80954504329',
    projectId: 'samyeonchoga',
    storageBucket: 'samyeonchoga.firebasestorage.app',
    iosBundleId: 'com.jinpyok.samyeonchoga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNcd5X-NFhoyev-d91CNBte6ReiJ6QOOY',
    appId: '1:80954504329:ios:db6a2ed17b1e9fd2c8c258',
    messagingSenderId: '80954504329',
    projectId: 'samyeonchoga',
    storageBucket: 'samyeonchoga.firebasestorage.app',
    iosBundleId: 'com.jinpyok.samyeonchoga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwUMlIUsmYomKjRsMVtUamtPTuthubqmw',
    appId: '1:80954504329:web:4e1b8d8a2d6ba4e3c8c258',
    messagingSenderId: '80954504329',
    projectId: 'samyeonchoga',
    authDomain: 'samyeonchoga.firebaseapp.com',
    storageBucket: 'samyeonchoga.firebasestorage.app',
    measurementId: 'G-CLDBYYD59R',
  );
}
